apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phoenix-liveview.fullname" . }}
  labels:
    {{- include "phoenix-liveview.labels" . | nindent 4 }}
data:
  PHX_HOST: {{ .Values.config.PHX_HOST | quote }}
  PORT: {{ .Values.config.PORT | quote }}
  POOL_SIZE: {{ .Values.config.POOL_SIZE | quote }}
  DATABASE_SSL: {{ .Values.config.DATABASE_SSL | quote }}
  {{- if .Values.database.caBundle.enabled }}
  DATABASE_SSL_CA_CERT: "/etc/ssl/rds/{{ .Values.database.caBundle.key }}"
  {{- end }}
  {{- range $k, $v := .Values.config.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
